class ClientEvent:
    """
    this class all the events which nessary for the CLIENT COMMUNICATION
    """

    CLIENT_REGISTER = "CLIENT_REGISTER"
    CLIENT_REGISTER_FAIL = "CLIENT_REGISTER_FAIL"
    CLIENT_REGISTER_SUCC = "CLIENT_REGISTER_SUCC"


    CLEINT_FUNCTION_REGISTER  = "CLEINT_FUNCTION_REGISTER"
    CLEINT_FUNCTION_REGISTER_FAIL = "CLEINT_FUNCTION_REGISTER_FAIL"
    CLEINT_FUNCTION_REGISTER_SUCC = "CLEINT_FUNCTION_REGISTER_SUCC"


    CLIENT_FUNCTION_CALL = "CLIENT_FUNCTION_CALL"
    CLIENT_FUNCTION_RETU = "CLIENT_FUNCTION_RETU"

class ManagerEvent:
    """
    this class have all the events which is nessary for the manager operation's
    """
    CLIENT_VERIFYED = "CLIENT_VERIFYED"
    CLIENT_VERIFYED_FAIL = "CLIENT_VERIFYED_FAIL"
    CLIENT_VERIFYED_SUCC = "CLIENT_VERIFYED_SUCC"


    CLIENT_FUNCTION_CALL = "CLIENT_FUNCTION_CALL"
    CLIENT_FUNCTION_RETU = "CLIENT_FUNCTION_RETU"

    INVALID_EVENT = "INVALID_EVENT"